version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    networks:
      - ecommerce-network
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
      - "5671:5671"
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: yjk9805/config-service:1.0
    container_name: config-service
    restart: always
    networks:
      - ecommerce-network
    ports:
      - "8888:8888"
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.profiles.active=default

networks:
  ecommerce-network:
    external: true
