version: '3.8'

services:
  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: yjk9805/catalog-service:1.0
    container_name: catalog-service
    restart: always
    networks:
      - ecommerce-network
    environment:
      - spring.cloud.config.name=ecommerce
      - spring.config.import=optional:configserver:http://config-service:8888
      - spring.rabbitmq.host=rabbitmq
      - spring.zipkin.base-url=http://zipkin:9411
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - logging.file=/api-logs/catalogs-ws.log

networks:
  ecommerce-network:
    external: true
