version: '3.8'

services:
  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: yjk9805/discovery-service:1.0
    container_name: discovery-service
    restart: always
    networks:
      - ecommerce-network
    ports:
      - "8761:8761"
    environment:
      - spring.cloud.config.uri=http://config-service:8888

networks:
  ecommerce-network:
    external: true
