server:
  port: 60000

spring:
  application:
    name: user-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
  datasource:
    generate-unique-name: false
#  profiles:
#    active: dev

greeting:
  message: Welcome to the Simple E-commerce

order-service-url: ${ORDER-SERVICE-URL}

logging:
  level:
    com.example.user: DEBUG
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

#token:
#  expiration_time: cloud config
#  secret: cloud config
management:
  endpoints:
    web:
      exposure:
        include: health, beans, busrefresh, info, metrics, prometheus

gateway:
  ip: ${GATEWAY_IP}

token:
  expiration_time: ${TOKEN_EXPIRATION_TIME}
  secret: ${TOKEN_SECRET}
