server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://locahost:8888
      name: ecommerce
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false