version: '3.8'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    image: yjk9805/mariadb-network:1.0
    container_name: mariadb-network
    restart: always
    networks:
      - ecommerce-network
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data/mysql:/var/lib/mysql

networks:
  ecommerce-network:
    external: true
